files:
  - source: /docs/*
    ignore:
      - /docs/CNAME
    translation: /%two_letters_code%/%original_path%/%original_file_name%
  - source: /docs/Dev-Guide/*
    translation: /%two_letters_code%/%original_path%/%original_file_name%
  - source: /docs/FAQs/*
    translation: /%two_letters_code%/%original_path%/%original_file_name%
  - source: /docs/Learn/
    translation: /%two_letters_code%/%original_path%/%original_file_name%
  - source: /docs/Node/
    translation: /%two_letters_code%/%original_path%/%original_file_name%
  - source: /docs/stake-and-delegate/
    translation: /%two_letters_code%/%original_path%/%original_file_name%
  - source: /docs/api/
    translation: /%two_letters_code%/%original_path%/%original_file_name%
